name: ml-music
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - jupyterlab
  - ipykernel
  - notebook
  - pytorch
  - torchaudio
  - librosa
  - mido
  - ffmpeg
  - pydub
  - pip
  - pip:
      - miditok
      - symusic
      - miditoolkit
      - midiutil